# -*- mode: ruby -*-
# vi: set ft=ruby :

# vagrant init
# vagrant box add hashicorp/precise64

Vagrant.configure("2") do |config|
	config.vm.box = "base"

	# config.vm.box_check_update = false

	config.vm.network :private_network, bridge: "nat", ip: "192.168.33.10"
	# config.vm.network "forwarded_port", guest: 80, host: 8080
	# config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
	# config.vm.network "private_network", ip: "192.168.33.10"
	# config.vm.network "public_network"
	# config.vm.synced_folder "../data", "/vagrant_data"

	config.vm.provider :hyperv do |provider|
		provider.cpus = 1
		provider.memory = 2048
		provider.maxmemory = 2048
	end

	# config.vm.provision "shell", inline: <<-SHELL
	#   apt-get update
	#   apt-get install -y apache2
	# SHELL
end
