---

# ansible -i hosts 127.0.0.1 -m ping
# ansible -i inventory/prometheus 192.168.1.1 -m ping

# ansible-playbook play-prometheus.yml -i inventory/prometheus
# ansible-playbook play-prometheus.yml -i 192.168.1.1
# ansible-playbook play-prometheus.yml -k -c MyPassword

- hosts: all
  sudo: yes
  vars:
    password: xxxx
  tasks:
    - debug: msg="hostname: {{ inventory_hostname }}"

- hosts: server
  sudo: yes
  #tasks:
  #  - name: hello
  #    user: 


#> wget https://github.com/prometheus/prometheus/releases/download/v2.10.0/prometheus-2.10.0.linux-amd64.tar.gz
#> tar zxvf prometheus-2.10.0.linux-amd64.tar.gz
#> mv prometheus-2.10.0.linux-amd64 promethus-server
#> cd promethus-server
#> cp prometheus.yml prometheus.yml.org



