---

# HOW-TO:
# cp inventory/prometheus-EXAMPLE inventory/prometheus
# vim inventory/prometheus

# ansible -i hosts 127.0.0.1 -m ping
# ansible -i inventory/prometheus 192.168.1.1 -m ping

# ansible-playbook play-prometheus.yml -i inventory/prometheus

- hosts: all
  become: yes
  tasks:
    - debug: msg="Hello, {{ inventory_hostname }}."

- hosts: prometheus
  become: yes
  vars_files:
    - vars/prometheus.yml
  vars:
    prom_path: ~/prometheus.tar.gz
    install_dir: /usr/local/src/prometheus/prometheus
  tasks:
    - name: Download tarball
      get_url: url={{ prom_url }} checksum={{ prom_checksum }} dest={{ prom_path }} force=no
      register: downloaded_tarball

    - name: Find out if (re-)install is necessary
      set_fact:
        need_to_install: "{{ downloaded_tarball | changed }}"

    - name: Clean up the installation directory
      file: path={{ install_dir }} state=absent
      when: need_to_install

    - name: Prepare the installation directory
      file: path={{ install_dir }} state=directory
      when: need_to_install

    - name: Unpack the tarball
      command: tar -zxf {{ prom_path }} -C {{ install_dir }} --strip-components=1
      when: need_to_install

    - name: Copy service file
      copy:
        src: ./files/prometheus.service
        dest: /lib/systemd/system/
    - name: Enable and start service
      systemd:
        enabled: yes
        state: started
        name: prometheus



#TODO cp prometheus.yml prometheus.yml.org



- hosts: node_exporter
  become: yes
  vars_files:
    - vars/prometheus.yml
  vars:
    install_dir: /usr/local/src/prometheus/node_exporter
  tasks:
    - name: Download tarball
      get_url: url={{ node_exporter_url }} checksum={{ node_exporter_checksum }} dest=~/ force=no
      register: tarball

    - name: Find out if (re-)install is necessary
      set_fact:
        need_to_install: "{{ tarball | changed }}"

    - name: Clean up the installation directory
      file: path={{ install_dir }} state=absent
      when: need_to_install

    - name: Prepare the installation directory
      file: path={{ install_dir }} state=directory
      when: need_to_install

    - name: Unpack the tarball
      command: tar -zxf {{ tarball.dest }} -C {{ install_dir }} --strip-components=1
      when: need_to_install

    - name: Copy service file
      copy:
        src: ./files/prometheus-node-exporter.service
        dest: /lib/systemd/system/
    - name: Enable and start service
      systemd:
        enabled: yes
        state: started
        name: prometheus-node-exporter


