# -*- mode: ruby -*-
# vi: set ft=ruby :

# vagrant init
# vagrant box add centos/7
# vagrant up
# vagrant ssh

Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"

	config.vm.network :private_network, bridge: "nat"
	#config.vm.network :private_network, ip: "192.168.33.10"

	config.vm.provider :hyperv do |provider|
		provider.vmname = "MyCentOS"
		provider.cpus = 1
		provider.memory = 2048
		provider.maxmemory = 2048
	end

	config.vm.provision "shell", inline: <<-SHELL
		yum update --obsoletes
		yum install epel-release
	SHELL
end
